name: storage_manager
description: Manages local storage.
version: 0.8.2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_download_manager:
    git:
      url: https://github.com/simplecohesion/flutter_download_manager
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
